### ISSUE TITLE
Checking Replication example use of pgbench not correct 

### ISSUE THREAD

**Issue by vitya-ne** [pgpool/pgpool2#12]
In section 7.1.2.2. Checking Replication of [7.1. Basic Configuration Example](http://www.pgpool.net/docs/latest/en/html/example-basic.html) incorrect table names created by [pgbench](https://www.postgresql.org/docs/current/static/pgbench.html) are used:
```
branches, tellers, accounts, history
```
All supported versions postgresql use the following table names:
```
pgbench_branches, pgbench_tellers, pgbench_accounts, pgbench_history
```
see [pgbench info](https://www.postgresql.org/docs/current/static/pgbench.html)

Please, update docs.

**Comment by pengbo0328** [comment]
Document typo is fixed.
https://git.postgresql.org/gitweb/?p=pgpool2.git;a=commit;h=045fe5c9c3d872cf5bc014b3a0df11393b3df930

**Comment by vitya-ne** [comment]
thanks
