### ISSUE TITLE
Latest Round of Tags has not synced

### ISSUE THREAD

**Issue by crunchyjoea** [pgpool/pgpool2#29]
The latest round of tags (4.0.5, 3.7.10, 3.6.17, 3.5.21 and 3.4.24) has not synced to this mirror. Typically they mirror to this repo from git.postgresql.org/git/pgpool2 fairly quickly.

**Comment by pengbo0328** [comment]
This mirror has been updated. We update this mirror daily.

**Comment by crunchyjoea** [comment]
Thank you!
