### ISSUE TITLE
/etc/sudoers.d/pgpool: bad permissions, should be mode 0440

### ISSUE THREAD

**Issue by Chethanravindra09** [pgpool/pgpool2#47]
Hello,

When we validate the sudoers through the visudo -c, it throwing the /etc/sudoers.d/pgpool: bad permissions, should be mode 0440
error, I think it's need to be fixed in the rpm. Because it added the pgpool sudoers in 640 permission, actually it should be 0440.

**Comment by pengbo0328** [comment]
@Chethanravindra09 Thank you for reporting this issue.

I have fixed the SPEC file 62fb831
It will be fixed in the next minor version releases.

**Comment by Chethanravindra09** [comment]
@pengbo0328 Thanks for fixing it. Will it apply it to all pgpool versions, like pgpool14  or  only for pgpool16

**Comment by Chethanravindra09** [comment]
Thanks for clarify it.
