### ISSUE TITLE
Not use LadBalance except Comment

### ISSUE THREAD

**Issue by itshikanov** [pgpool/pgpool2#51]
hello.
I'm try to not load balance all except specific queryes with comment.
Not found specific config option, but i thought that regexp Negative Lookahead `^((?!LOAD_BALANCE).)*$` in primary_routing_query_pattern_list option will work. But it didn`t.

The part of my config is
```
load_balance_mode = on
statement_level_load_balance  = on
allow_sql_comments = on
primary_routing_query_pattern_list = '^((?!LOAD_BALANCE).)*$'
```

This regexp work well here for example https://regex101.com/. Accept all query except LOAD_BALANCE. But it did not work in pgpool2. This is BUG or expected behaviour?

If this is expected. How to do what i need?

**Comment by tatsuo-ishii** [comment]
I am going to close this issue. If you have additional issues regarding this, please re-open the issue.

**Comment by tatsuo-ishii** [comment]
Issue closed.
