### ISSUE TITLE
pg's tcp_keepalives_idle is not transport to client

### ISSUE THREAD

**Issue by NiuBlibing** [pgpool/pgpool2#57]
`tcp_keepalives_idle` seems not work  between pgpool and pg client which is very useful for k8s environments.

**Comment by pengbo0328** [comment]
@NiuBlibing 

> tcp_keepalives_idle seems not work between pgpool and pg client which is very useful for k8s environments.

If  you are using pgpool, pgpool is the client of PostgreSQL.
The connection between pgpool and PostgreSQL will be maintained even if the client is disconnected.
It is the feature of connection pooling.

We have a similar feature in pgpool to close the idle connection using `client_idle_limit`.

https://www.pgpool.net/docs/latest/en/html/runtime-config-connection-pooling.html#GUC-CLIENT-IDLE-LIMIT

>Specifies the time in seconds to disconnect a client if it remains idle since the last query. 
> This is useful for preventing the Pgpool-II children from being occupied by a lazy clients or broken TCP/IP connection between client and Pgpool-II. 

But I'm not sure if this is the feature you want.
May I ask your usecase which require this feature?

**Comment by pengbo0328** [comment]
@NiuBlibing May I close this issue?

**Comment by NiuBlibing** [comment]
Thank you.
