### ISSUE TITLE
Pgpool doesn't start automatically for RHEL 

### ISSUE THREAD

**Issue by MaryTishchenkova** [pgpool/pgpool2#58]
Hello, 
It was discovered that pgpool does not start automatically on RHEL VMs, there is no such problem on Ubuntu.  Could you please fix this?

**Comment by pengbo0328** [comment]
@MaryTishchenkova 
> Hello,
> It was discovered that pgpool does not start automatically on RHEL VMs, there is no such problem on Ubuntu. Could you please fix this?

Does this mean that even if `systemctl enable pgpool` is set, the pgpool service will not start automatically?
Are you using `systemctl status pgpool` command to check the status of pgpool service?

Are you using the RPM for RHEL provided by pgpool community?
https://www.pgpool.net/mediawiki/index.php/Downloads
If you are not using the RPM provided by pgpool community, I think you need to check the service file.

**Comment by MaryTishchenkova** [comment]
Usually I follow these steps: 

1. Enable the repo (from https://download.postgresql.org/pub/repos/yum/)
2. Install pgpool package using yum
3. Manually enable and start the service

```
# systemctl status pgpool-II.service
pgpool-II.service - PGPool-II Middleware Between PostgreSQL Servers And PostgreSQL Database Clients
     Loaded: loaded (/usr/lib/systemd/system/pgpool-II.service; disabled; preset: disabled)
     Active: inactive (dead)
     
# systemctl enable pgpool-II.service
Created symlink /etc/systemd/system/multi-user.target.wants/pgpool-II.service → /usr/lib/systemd/system/pgpool-II.service.
# systemctl status pgpool-II.service
pgpool-II.service - PGPool-II Middleware Between PostgreSQL Servers And PostgreSQL Database Clients
     Loaded: loaded (/usr/lib/systemd/system/pgpool-II.service; enabled; preset: disabled)
     Active: inactive (dead)

# systemctl start pgpool-II.service
# systemctl status pgpool-II.service
pgpool-II.service - PGPool-II Middleware Between PostgreSQL Servers And PostgreSQL Database Clients
     Loaded: loaded (/usr/lib/systemd/system/pgpool-II.service; enabled; preset: disabled)
     Active: active (running) since Mon 2024-07-08 10:00:12 CEST; 1s ago
     
```

For ubuntu I avoid 3 step. Is it possible to automate this step for RHEL on the package side as well?

**Comment by pengbo0328** [comment]
@MaryTishchenkova 
> Usually I follow these steps:
> 
>     Enable the repo (from https://download.postgresql.org/pub/repos/yum/)

You are using the RPM provided by PostgreSQL community.
I think you need to check the pgpool systemd service file to see if pgpool is waiting for other services to start.
Alternatively, please contact the PostgreSQL community because the systemd service file is created by packager.

The RPMs provided by Pgpool-II community is [here](https://www.pgpool.net/yum/rpms/)

**Comment by pengbo0328** [comment]
> Usually I follow these steps:
> 
>     Enable the repo (from https://download.postgresql.org/pub/repos/yum/)

You are using the RPM provided by PostgreSQL community.

It seems it is depends on your systemd setting, it is not a pgpool issue.
I think it is required to set `systemctl enable pgpool-II.service` to enable start pgpool automatically.

**Comment by MaryTishchenkova** [comment]
Yes, but the question is, will this process be automated like for Ubuntu? To avoid performing manual commands like `systemctl enable pgpool-II.service`

**Comment by MaryTishchenkova** [comment]
@tatsuo-ishii  thanks :)

**Comment by pengbo0328** [comment]
@MaryTishchenkova 
> Yes, but the question is, will this process be automated as for Ubuntu? To avoid performing manual commands like systemctl enable pgpool-II.service

Just installing the RPM will not automatically start the service on RHEL. Other services have same behavior on RHEL.
I think it is RHEL RPM management policy.

**Comment by MaryTishchenkova** [comment]
@pengbo0328 It's possible to enable this as post-installation step, but I will write to the PostgreSQL community and ask about this. Thanks guys!
