### ISSUE TITLE
Error on SCRAM auth : "HINT:  verify the valid pool_key exists"

### ISSUE THREAD

**Issue by DB-CL** [pgpool/pgpool2#60]
**Problem encoutered**

When I setup SCRAM Auth, I cannot auth to pgpool2, I get the following error : 

```bash
$ psql -h 192.168.56.14 -p 9999 -U dev -d benchmark_db
psql: error: connection to server at "192.168.56.14", port 9999 failed: ERROR:  SCRAM authentication failed
DETAIL:  unable to decrypt password from pool_passwd
HINT:  verify the valid pool_key exists
```

**Steps to reproduce**
_pgpool.conf_ (relevant lines)
```
enable_pool_hba = on
pool_passwd = 'pool_passwd'
allow_clear_text_frontend_auth = off
```
_pool_hba.conf_
```
# TYPE  DATABASE    USER        CIDR-ADDRESS          METHOD
local   all         all                               trust
host    all         all         127.0.0.1/32          trust
host    all         all         ::1/128               trust
host    all         all         192.168.56.0/24       scram-sha-256
```

_user creation_
```bash
$ echo "big secret" > /etc/pgpool2/.pgpoolkey
$ pg_enc -m -k /etc/pgpool2/.pgpoolkey -f /etc/pgpool2/pgpool.conf -u dev dev
$ cat /etc/pgpool2/pool_passwd
dev:AES54xLUZ9PJbagrGosogJayQ==
```

_cluster info_
  - pgpool ip : 192.168.56.14/24
  - backend ips : 192.168.56.11-13/24
  - I don't see any log line in the postgres backend, so I think it's not a postgres problem. I think the problem occurs at pgpool level

I've read the documentation again and again, maybe I missed something but I have no clue atm. Is it a bug ?

**Comment by pengbo0328** [comment]
@DB-CL 
By default the Pgpool-II will look for the .pgpoolkey file in the user's home directory or the file referenced by environment variable `PGPOOLKEYFILE`. 
If your key file is in `/etc/pgpool2/`, you need to specify the key file using the (-k, --key-file=KEY_FILE) command line argument to the [pgpool](https://www.pgpool.net/docs/latest/en/html/pgpool.html) command.

**Comment by DB-CL** [comment]
Just tested and it works. Thank you for the pointer !
