### ISSUE TITLE
Transactional continuity question

### ISSUE THREAD

**Issue by Sudingyi** [pgpool/pgpool2#74]
Hello I want to ask when I connect to the pgpool back-end cluster to switch, if I am a write operation failed in read and write separation, the subsequent execution is still in a transaction？

**Comment by pengbo0328** [comment]
> Hello I want to ask when I connect to the pgpool back-end cluster to switch, if I am a write operation failed in read and write separation, the subsequent execution is still in a transaction？

If a write query fails, the transaction will be aborted, and subsequent queries will be ignored until the end of the transaction block.

**Comment by Sudingyi** [comment]
> > Hello I want to ask when I connect to the pgpool back-end cluster to switch, if I am a write operation failed in read and write separation, the subsequent execution is still in a transaction？
> 
> If a write query fails, the transaction will be aborted, and subsequent queries will be ignored until the end of the transaction block.

Ignoring means that the client gets a failed exception when the subsequent transaction is queried.The user will not get the information of transaction termination or rollback.Only when the user opens the next new transaction will it be processed normally. I hope you will reply again thank you.

**Comment by pengbo0328** [comment]
> Ignoring means that the client gets a failed exception when the subsequent transaction is queried.The user will not get the information of transaction termination or rollback.
Yes. The queries fail unless you run an abort or rollback.
>Only when the user opens the next new transaction will it be processed normally. 
Yes.
