### ISSUE TITLE
Who are `pop_user` & `wide` on `pool_hba.conf`?

### ISSUE THREAD

**Issue by yukha-dw** [pgpool/pgpool2#75]
Hello, can anyone explain to me why people add `pop_user` & `wide` users to `pool_hba.conf` with `trust` authentication? For example, bitnami's adds them on default, but I don't see any usage nor activity on my database.
https://github.com/bitnami/containers/blob/2de4377adaaa5ba0ba682bc1aa62747cea63bc22/bitnami/pgpool/4/debian-12/rootfs/opt/bitnami/scripts/libpgpool.sh#L365-L372

```
host     all             wide               all         trust
host     all             pop_user           all         trust
```

Thank you in advance!

**Comment by tatsuo-ishii** [comment]
I think it's specific with bitnami container. As a pgpool developer, I don't know what bitnami people think why they needed to add them to pool_hba.conf. I suggest you to ask bitnami deveopers.

**Comment by yukha-dw** [comment]
> I think it's specific with bitnami container. As a pgpool developer, I don't know what bitnami people think why they needed to add them to pool_hba.conf. I suggest you to ask bitnami deveopers.

@tatsuo-ishii got it, thanks!
