### ISSUE TITLE
How to distribute PLSQL statements in a read/write splitting cluster

### ISSUE THREAD

**Issue by Sudingyi** [pgpool/pgpool2#76]
If I enter a plsql statement, how does pgpool perform read/write splitting recognition?

**Comment by tatsuo-ishii** [comment]
> If I enter a plsql statement,
Do you mean a function written in PL/pgSQL and call it using SELECT?

**Comment by Sudingyi** [comment]
Yes, but not limited to that.It also includes some statements that start with declare.These will be recognized as write statements and sent to the master

**Comment by Sudingyi** [comment]
ok. thank you
